A.A1 = "Words"
A.A2 = "Error code: {errorCode:int}"
A.A3 = "Error: {error}"
A.A4.A41 = "Warning: {error}"
A.A4.A42 = "Tip: {0}={1}"
B.C.A1 = "Hello"
B.C.A2.A3 = "Hello"
B.C.A2.A4.Add.A1123.Sddd.Ffffff.Cxzzxc = "Hello"
B.D.A2.A4.Add.A1123.Sddd.Ffffff.Cxzzxc = "Hello"
