//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetCampus.Localizations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotnetCampus.Localizations.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string DLA000 {
            get {
                return ResourceManager.GetString("DLA000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. {0}.
        /// </summary>
        public static string DLA000_Message {
            get {
                return ResourceManager.GetString("DLA000_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language tag does not exist.
        /// </summary>
        public static string DLA001 {
            get {
                return ResourceManager.GetString("DLA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default language tag &quot;{0}&quot; is not in the supported language list, which is: {1}..
        /// </summary>
        public static string DLA001_Message {
            get {
                return ResourceManager.GetString("DLA001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language tag does not exist.
        /// </summary>
        public static string DLA002 {
            get {
                return ResourceManager.GetString("DLA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current language tag &quot;{0}&quot; is not in the supported language list, which is: {1}..
        /// </summary>
        public static string DLA002_Message {
            get {
                return ResourceManager.GetString("DLA002_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current language tag &quot;{0}&quot; is not in the supported language list, which is: {1}..
        /// </summary>
        public static string DLA002_Message1 {
            get {
                return ResourceManager.GetString("DLA002_Message1", resourceCulture);
            }
        }
    }
}
