//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetCampus.Localizations.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotnetCampus.Localizations.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Error 的本地化字符串。
        /// </summary>
        public static string DLA000 {
            get {
                return ResourceManager.GetString("DLA000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occurred. {0} 的本地化字符串。
        /// </summary>
        public static string DLA000_Message {
            get {
                return ResourceManager.GetString("DLA000_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 language tag does not exist 的本地化字符串。
        /// </summary>
        public static string DLA001 {
            get {
                return ResourceManager.GetString("DLA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default language tag &quot;{0}&quot; is not in the supported language list, which is: {1}. 的本地化字符串。
        /// </summary>
        public static string DLA001_Message {
            get {
                return ResourceManager.GetString("DLA001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current language tag does not exist 的本地化字符串。
        /// </summary>
        public static string DLA002 {
            get {
                return ResourceManager.GetString("DLA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current language tag &quot;{0}&quot; is not in the supported language list, which is: {1}. 的本地化字符串。
        /// </summary>
        public static string DLA002_Message {
            get {
                return ResourceManager.GetString("DLA002_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current language tag &quot;{0}&quot; is not in the supported language list, which is: {1}. 的本地化字符串。
        /// </summary>
        public static string DLA002_Message1 {
            get {
                return ResourceManager.GetString("DLA002_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language key inconsistent. 的本地化字符串。
        /// </summary>
        public static string DLA003 {
            get {
                return ResourceManager.GetString("DLA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language key inconsistent. {0} 的本地化字符串。
        /// </summary>
        public static string DLA003_Message {
            get {
                return ResourceManager.GetString("DLA003_Message", resourceCulture);
            }
        }
    }
}
